### ISSUE TITLE
Failing: ValueError: Unknown status message: 'IMPORT_OK'

### ISSUE THREAD

**Issue by dev-korr** [crashvb/docker-sign-verify#3]
Please find the trace log below.

root@0af4e28dff4b:/# docker-sign -d registry -k $KEY -p $MYPASSWORD $SRC_IMAGE:$VERSION $DEST_IMAGE:$VERSION
DEBUG:docker_sign_verify.signers:Using trust store: /root/.gnupg
INFO:docker_sign_verify.imagesources:Signing: $SRC_IMAGE:$VERSION ...
INFO:docker_sign_verify.imagesources:Verifying Integrity: $SRC_IMAGE:$VERSION ...
DEBUG:docker_sign_verify.imagesources:Using credentials store: /root/.docker/config.json
DEBUG:docker_sign_verify.imagesources:    config digest: sha256:c7b48e4c99186...df2e81ed87f998db3
DEBUG:docker_sign_verify.imagesources:    manifest layers:
                        sha256:92058cf440533...7a55b1dcda11af599
                        sha256:8d846904080d3...b6cb986aaa7df3134
                        sha256:c63c3ce00c0ec...a137e6d7fe4d1c491
                        sha256:e5bce453061a4...a1aba55598fdb8da7
DEBUG:docker_sign_verify.imagesources:    image layers:
                        sha256:20a1b4e9f75b3...d17b1dd2ae37fd717
                        sha256:8a325f8a1c47d...44a6e4127edb74d7f
                        sha256:4e279eff923e6...a3505bc41bc796cb4
                        sha256:c5b9af0a8c8c3...5ffcea1ecd2ecafb4
INFO:docker_sign_verify.imagesources:Integrity check passed.
WARNING:gnupg:unsafe ownership on homedir '/root/.gnupg'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/gnupg/_meta.py", line 650, in _read_response
    result._handle_status(keyword, value)
  File "/usr/local/lib/python3.7/site-packages/gnupg/_parsers.py", line 1094, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'IMPORT_OK'

Traceback (most recent call last):
  File "/usr/local/bin/docker-sign", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker_sign_verify/scripts/docker_sign.py", line 148, in registry
    sign(context)
  File "/usr/local/lib/python3.7/site-packages/docker_sign_verify/scripts/docker_sign.py", line 83, in sign
    context.obj["dest_image_name"],
  File "/usr/local/lib/python3.7/site-packages/docker_sign_verify/imagesources.py", line 884, in sign_image
    data = self._sign_image_config(signer, src_image_name)
  File "/usr/local/lib/python3.7/site-packages/docker_sign_verify/imagesources.py", line 78, in _sign_image_config
    signature_value = image_config.sign(signer)
  File "/usr/local/lib/python3.7/site-packages/docker_sign_verify/imageconfig.py", line 257, in sign
    raise RuntimeError("Failed to create signature!")
RuntimeError: Failed to create signature!
root@0af4e28dff4b:/#

**Comment by crashvb** [comment]
Looks like an issue with the underlying `gnupg` library.
