### ISSUE TITLE
Failing with KeyError: 'Labels'

### ISSUE THREAD

**Issue by dev-korr** [crashvb/docker-sign-verify#6]
I have patched the file (/lib/python3.7/site-packages/docker_sign_verify/imageconfig.py) with line below as suggested, still not working.

      return config_json["config"].get("Labels", {})

**Comment by dev-korr** [comment]
I'm using latest version 0.4.2 and still see this error from #issue6.  

$ docker-sign version
0.4.2

**Please find the full trace log below:**

DEBUG:docker_sign_verify.imagesources:Integrity check passed.
Traceback (most recent call last):
  File "/tmp/tag/lib/python3.7/site-packages/docker_sign_verify/imageconfig.py", line 85, in _get_labels
    labels = config_json[key]["Labels"]
KeyError: 'Config'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/tag/bin/docker-sign", line 11, in <module>
    sys.exit(cli())
  File "/tmp/tag/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/tag/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/tmp/tag/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/tag/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/tag/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/tag/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/tag/lib/python3.7/site-packages/docker_sign_verify/scripts/docker_sign.py", line 153, in registry
    sign(context)
  File "/tmp/tag/lib/python3.7/site-packages/docker_sign_verify/scripts/docker_sign.py", line 83, in sign
    context.obj["dest_image_name"],
  File "/tmp/tag/lib/python3.7/site-packages/docker_sign_verify/imagesources.py", line 943, in sign_image
    data = self._sign_image_config(signer, src_image_name)
  File "/tmp/tag/lib/python3.7/site-packages/docker_sign_verify/imagesources.py", line 87, in _sign_image_config
    signature_value = image_config.sign(signer)
  File "/tmp/tag/lib/python3.7/site-packages/docker_sign_verify/imageconfig.py", line 261, in sign
    signature_data = self.get_signature_data()
  File "/tmp/tag/lib/python3.7/site-packages/docker_sign_verify/imageconfig.py", line 211, in get_signature_data
    labels = ImageConfig._get_labels(self.config_json)
  File "/tmp/tag/lib/python3.7/site-packages/docker_sign_verify/imageconfig.py", line 88, in _get_labels
    labels = config_json[key]["Labels"]
KeyError: 'Labels'
